#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="peashake")]
public partial class HelpDeskDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertMessage(Message instance);
  partial void UpdateMessage(Message instance);
  partial void DeleteMessage(Message instance);
  #endregion
	
	public HelpDeskDataContext() :
      base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ApplicationServices"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public HelpDeskDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HelpDeskDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HelpDeskDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HelpDeskDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Customer> Customers
	{
		get
		{
			return this.GetTable<Customer>();
		}
	}
	
	public System.Data.Linq.Table<Message> Message
	{
		get
		{
			return this.GetTable<Message>();
		}
	}

    public System.Data.Linq.Table<Notice> Notice
    {
        get
        {
            return this.GetTable<Notice>();
        }
    }
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customers")]
public partial class Customer
{
	
	private string _CustomerID;
	
	private string _CompanyName;
	
	private string _ContactName;
	
	private string _ContactTitle;
	
	private string _Address;
	
	private string _City;
	
	private string _Region;
	
	private string _PostalCode;
	
	private string _Country;
	
	private string _Phone;
	
	private string _Fax;
	
	private System.Nullable<bool> _Bool;
	
	public Customer()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="NChar(5) NOT NULL", CanBeNull=false)]
	public string CustomerID
	{
		get
		{
			return this._CustomerID;
		}
		set
		{
			if ((this._CustomerID != value))
			{
				this._CustomerID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
	public string CompanyName
	{
		get
		{
			return this._CompanyName;
		}
		set
		{
			if ((this._CompanyName != value))
			{
				this._CompanyName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="NVarChar(30)")]
	public string ContactName
	{
		get
		{
			return this._ContactName;
		}
		set
		{
			if ((this._ContactName != value))
			{
				this._ContactName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactTitle", DbType="NVarChar(30)")]
	public string ContactTitle
	{
		get
		{
			return this._ContactTitle;
		}
		set
		{
			if ((this._ContactTitle != value))
			{
				this._ContactTitle = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(60)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this._Address = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(15)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this._City = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="NVarChar(15)")]
	public string Region
	{
		get
		{
			return this._Region;
		}
		set
		{
			if ((this._Region != value))
			{
				this._Region = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="NVarChar(10)")]
	public string PostalCode
	{
		get
		{
			return this._PostalCode;
		}
		set
		{
			if ((this._PostalCode != value))
			{
				this._PostalCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(15)")]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this._Country = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(24)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this._Phone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(24)")]
	public string Fax
	{
		get
		{
			return this._Fax;
		}
		set
		{
			if ((this._Fax != value))
			{
				this._Fax = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bool", DbType="Bit")]
	public System.Nullable<bool> Bool
	{
		get
		{
			return this._Bool;
		}
		set
		{
			if ((this._Bool != value))
			{
				this._Bool = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Message")]
public partial class Message : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _MessageID;

    private string _UserId;

    private string _Folder;
	
	private string _Body;
	
	private string _From;

    private string _To;

    private string _Subject;
	
	private System.Nullable<System.DateTime> _Sent;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMessageIDChanging(long value);
    partial void OnMessageIDChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnFolderChanging(string value);
    partial void OnFolderChanged();
    partial void OnBodyChanging(string value);
    partial void OnBodyChanged();
    partial void OnFromChanging(string value);
    partial void OnFromChanged();
    partial void OnToChanging(string value);
    partial void OnToChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnSentChanging(System.Nullable<System.DateTime> value);
    partial void OnSentChanged();
    #endregion
	
	public Message()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public long MessageID
	{
		get
		{
			return this._MessageID;
		}
		set
		{
			if ((this._MessageID != value))
			{
				this.OnMessageIDChanging(value);
				this.SendPropertyChanging();
				this._MessageID = value;
				this.SendPropertyChanged("MessageID");
				this.OnMessageIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Folder", DbType="NVarChar(256)")]
	public string Folder
	{
		get
		{
			return this._Folder;
		}
		set
		{
			if ((this._Folder != value))
			{
				this.OnFolderChanging(value);
				this.SendPropertyChanging();
				this._Folder = value;
				this.SendPropertyChanged("Folder");
				this.OnFolderChanged();
			}
		}
	}

    [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UserId", DbType = "NVarChar(256)")]
    public string UserId
    {
        get
        {
            return this._UserId;
        }
        set
        {
            if ((this._UserId != value))
            {
                this.OnUserIdChanging(value);
                this.SendPropertyChanging();
                this._UserId = value;
                this.SendPropertyChanged("UserId");
                this.OnUserIdChanged();
            }
        }
    }

    [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Body", DbType = "NVarChar(MAX)")]
	public string Body
	{
		get
		{
			return this._Body;
		}
		set
		{
			if ((this._Body != value))
			{
				this.OnBodyChanging(value);
				this.SendPropertyChanging();
				this._Body = value;
				this.SendPropertyChanged("Body");
				this.OnBodyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[From]", Storage="_From", DbType="NVarChar(256)")]
	public string From
	{
		get
		{
			return this._From;
		}
		set
		{
			if ((this._From != value))
			{
				this.OnFromChanging(value);
				this.SendPropertyChanging();
				this._From = value;
				this.SendPropertyChanged("From");
				this.OnFromChanged();
			}
		}
	}

    [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "[To]", Storage = "_To", DbType = "NVarChar(256)")]
    public string To
    {
        get
        {
            return this._To;
        }
        set
        {
            if ((this._To != value))
            {
                this.OnToChanging(value);
                this.SendPropertyChanging();
                this._To = value;
                this.SendPropertyChanged("To");
                this.OnToChanged();
            }
        }
    }

    [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Subject", DbType = "NVarChar(256)")]
	public string Subject
	{
		get
		{
			return this._Subject;
		}
		set
		{
			if ((this._Subject != value))
			{
				this.OnSubjectChanging(value);
				this.SendPropertyChanging();
				this._Subject = value;
				this.SendPropertyChanged("Subject");
				this.OnSubjectChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sent", DbType="DateTime")]
	public System.Nullable<System.DateTime> Sent
	{
		get
		{
			return this._Sent;
		}
		set
		{
			if ((this._Sent != value))
			{
				this.OnSentChanging(value);
				this.SendPropertyChanging();
				this._Sent = value;
				this.SendPropertyChanged("Sent");
				this.OnSentChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.Notice")]
public partial class Notice : INotifyPropertyChanging, INotifyPropertyChanged
{

    private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

    private long _NoticeID;

    private string _Folder;

    private string _CreatorId;

    private string _RecipientId;

    private string _Subject;

    private string _Body;

    private System.Nullable<System.DateTime> _CreateTimeStamp;

    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoticeIDChanging(long value);
    partial void OnNoticeIDChanged();
    partial void OnFolderChanging(string value);
    partial void OnFolderChanged();
    partial void OnCreatorIdChanging(string value);
    partial void OnCreatorIdChanged();
    partial void OnRecipientIdChanging(string value);
    partial void OnRecipientIdChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnBodyChanging(string value);
    partial void OnBodyChanged();
    partial void OnCreateTimeStampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateTimeStampChanged();
    #endregion

    public Notice()
    {
        OnCreated();
    }

    [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NoticeID", AutoSync = AutoSync.OnInsert, DbType = "BigInt NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
    public long NoticeID
    {
        get
        {
            return this._NoticeID;
        }
        set
        {
            if ((this._NoticeID != value))
            {
                this.OnNoticeIDChanging(value);
                this.SendPropertyChanging();
                this._NoticeID = value;
                this.SendPropertyChanged("NoticeID");
                this.OnNoticeIDChanged();
            }
        }
    }

    [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Folder", DbType = "NVarChar(256)")]
    public string Folder
    {
        get
        {
            return this._Folder;
        }
        set
        {
            if ((this._Folder != value))
            {
                this.OnFolderChanging(value);
                this.SendPropertyChanging();
                this._Folder = value;
                this.SendPropertyChanged("Folder");
                this.OnFolderChanged();
            }
        }
    }

    [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CreatorId", DbType = "NVarChar(256)")]
    public string CreatorId
    {
        get
        {
            return this._CreatorId;
        }
        set
        {
            if ((this._CreatorId != value))
            {
                this.OnCreatorIdChanging(value);
                this.SendPropertyChanging();
                this._CreatorId = value;
                this.SendPropertyChanged("CreatorId");
                this.OnCreatorIdChanged();
            }
        }
    }

    [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RecipientId", DbType = "NVarChar(256)")]
    public string RecipientId
    {
        get
        {
            return this._RecipientId;
        }
        set
        {
            if ((this._RecipientId != value))
            {
                this.OnRecipientIdChanging(value);
                this.SendPropertyChanging();
                this._RecipientId = value;
                this.SendPropertyChanged("RecipientId");
                this.OnRecipientIdChanged();
            }
        }
    }

    [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Subject", DbType = "NVarChar(256)")]
    public string Subject
    {
        get
        {
            return this._Subject;
        }
        set
        {
            if ((this._Subject != value))
            {
                this.OnSubjectChanging(value);
                this.SendPropertyChanging();
                this._Subject = value;
                this.SendPropertyChanged("Subject");
                this.OnSubjectChanged();
            }
        }
    }

    [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Body", DbType = "NVarChar(MAX)")]
    public string Body
    {
        get
        {
            return this._Body;
        }
        set
        {
            if ((this._Body != value))
            {
                this.OnBodyChanging(value);
                this.SendPropertyChanging();
                this._Body = value;
                this.SendPropertyChanged("Body");
                this.OnBodyChanged();
            }
        }
    }

    [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CreateTimeStamp", DbType = "DateTime")]
    public System.Nullable<System.DateTime> CreateTimeStamp
    {
        get
        {
            return this._CreateTimeStamp;
        }
        set
        {
            if ((this._CreateTimeStamp != value))
            {
                this.OnCreateTimeStampChanging(value);
                this.SendPropertyChanging();
                this._CreateTimeStamp = value;
                this.SendPropertyChanged("CreateTimeStamp");
                this.OnCreateTimeStampChanged();
            }
        }
    }

    public event PropertyChangingEventHandler PropertyChanging;

    public event PropertyChangedEventHandler PropertyChanged;

    protected virtual void SendPropertyChanging()
    {
        if ((this.PropertyChanging != null))
        {
            this.PropertyChanging(this, emptyChangingEventArgs);
        }
    }

    protected virtual void SendPropertyChanged(String propertyName)
    {
        if ((this.PropertyChanged != null))
        {
            this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
#pragma warning restore 1591
